# Netlify configuration file for DocifyByMe
[build]
  command = "npm run build && npm run postbuild"

[build.environment]
  NODE_VERSION = "18"

# Enable Next.js plugin for optimal performance
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Let the Netlify Next.js plugin manage API routes and publish directory
# (do not override with custom /api/* or global fallback redirects)

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Cache static assets for better performance
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# CORS headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Optional: add project-specific redirects here if needed (avoid catching /api/* or global /*)
