# Netlify configuration file for DocifyByMe
[build]
  command = "npm run build && npm run postbuild"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Enable Next.js plugin for optimal performance
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js App Router routing properly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Client-side routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Cache static assets for better performance
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# CORS headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Handle client-side routing
[[redirects]]
  from = "/dashboard"
  to = "/dashboard/"
  status = 301

[[redirects]]
  from = "/login"
  to = "/login/"
  status = 301
